<?php

return [
    [
        'key' => 'general',
        'name' => 'General',
        'info' => 'Core application defaults and newsroom-wide preferences.',
        'sort' => 1,
        'icon' => 'GE',
    ],
    [
        'key' => 'general.application',
        'name' => 'Application Defaults',
        'info' => 'Base placeholders for timezone, locale, and editorial defaults.',
        'sort' => 1,
        'fields' => [],
    ],
    [
        'key' => 'website',
        'name' => 'Website',
        'info' => 'Public-facing identity and structural site information.',
        'sort' => 2,
        'icon' => 'WE',
    ],
    [
        'key' => 'website.identity',
        'name' => 'Site Identity',
        'info' => 'Manage the public site name and logo assets used across the frontend shell.',
        'sort' => 1,
        'fields' => [
            [
                'key' => 'website.identity.site_name',
                'label' => 'Site Name',
                'type' => 'text',
                'required' => true,
                'placeholder' => 'NewsTech',
                'hint' => 'Used in the frontend header, fallback branding, and SEO title defaults.',
            ],
            [
                'key' => 'website.identity.logo_path',
                'label' => 'Primary Logo',
                'type' => 'image',
                'hint' => 'Upload the main site logo shown in the frontend header. PNG and WebP work well for light backgrounds.',
            ],
            [
                'key' => 'website.identity.footer_logo_path',
                'label' => 'Footer Logo',
                'type' => 'image',
                'hint' => 'Optional alternate logo for the footer. Leave empty to reuse the main branding mark.',
            ],
        ],
    ],
    [
        'key' => 'website.homepage',
        'name' => 'Homepage Layout',
        'info' => 'Choose how the homepage content column behaves and what appears in the optional right rail.',
        'sort' => 2,
        'fields' => [
            [
                'key' => 'website.homepage.layout',
                'label' => 'Homepage Layout',
                'type' => 'select',
                'required' => true,
                'options' => [
                    'full_width' => '100% Full Width',
                    'two_column_70_30' => '70 / 30 Two Column',
                ],
                'hint' => 'The two-column option keeps the current homepage feed on the left and introduces a configurable sidebar on the right.',
            ],
            [
                'key' => 'website.homepage.sidebar_title',
                'label' => 'Sidebar Title',
                'type' => 'text',
                'placeholder' => 'Inside NewsTech',
                'hint' => 'Shown above the homepage right-rail content when the 70 / 30 layout is active.',
            ],
            [
                'key' => 'website.homepage.sidebar_content',
                'label' => 'Sidebar Content',
                'type' => 'textarea',
                'rows' => 5,
                'placeholder' => 'Add a short editorial note, promo, or supporting homepage message.',
                'hint' => 'Keep this compact. It is meant for a simple foundation block, not a page builder.',
            ],
            [
                'key' => 'website.homepage.sidebar_link_label',
                'label' => 'Sidebar Link Label',
                'type' => 'text',
                'placeholder' => 'Read more',
                'hint' => 'Optional call-to-action label for the homepage sidebar block.',
            ],
            [
                'key' => 'website.homepage.sidebar_link_url',
                'label' => 'Sidebar Link URL',
                'type' => 'url',
                'placeholder' => 'https://example.com/about',
                'hint' => 'Optional URL paired with the sidebar call-to-action label.',
            ],
        ],
    ],
    [
        'key' => 'seo',
        'name' => 'SEO',
        'info' => 'Search metadata defaults and discovery-related controls.',
        'sort' => 3,
        'icon' => 'SE',
    ],
    [
        'key' => 'comments',
        'name' => 'Comments',
        'info' => 'Comment availability, moderation, and anti-spam controls.',
        'sort' => 4,
        'icon' => 'CO',
    ],
    [
        'key' => 'comments.moderation',
        'name' => 'Comment Behavior',
        'info' => 'Control whether comments are open, who can submit them, and how new entries are moderated.',
        'sort' => 1,
        'fields' => [
            [
                'key' => 'comments.enabled',
                'label' => 'Enable Comments',
                'type' => 'toggle',
                'hint' => 'Turn article comments on or off across the public site.',
            ],
            [
                'key' => 'comments.guest_comments_enabled',
                'label' => 'Allow Guest Comments',
                'type' => 'toggle',
                'hint' => 'Disable this if you want to pause anonymous submissions without removing approved comments.',
            ],
            [
                'key' => 'comments.require_moderation',
                'label' => 'Require Moderation',
                'type' => 'toggle',
                'hint' => 'When enabled, normal comments stay pending until an admin approves them.',
            ],
            [
                'key' => 'comments.website_field_enabled',
                'label' => 'Show Website Field',
                'type' => 'toggle',
                'hint' => 'Hide the optional website field on the public form if you want a simpler comment flow.',
            ],
            [
                'key' => 'comments.min_comment_length',
                'label' => 'Minimum Comment Length',
                'type' => 'number',
                'required' => true,
                'placeholder' => '5',
                'hint' => 'Reject very short comments before they enter the moderation queue.',
            ],
            [
                'key' => 'comments.max_comment_length',
                'label' => 'Maximum Comment Length',
                'type' => 'number',
                'required' => true,
                'placeholder' => '2000',
                'hint' => 'Cap the size of each submitted comment to keep moderation practical.',
            ],
        ],
    ],
    [
        'key' => 'comments.protection',
        'name' => 'Anti-Spam Rules',
        'info' => 'Basic spam controls without third-party services or CAPTCHA.',
        'sort' => 2,
        'fields' => [
            [
                'key' => 'comments.max_links_per_comment',
                'label' => 'Maximum Links Per Comment',
                'type' => 'number',
                'required' => true,
                'placeholder' => '2',
                'hint' => 'Comments with more links than this are treated as spam.',
            ],
            [
                'key' => 'comments.throttle_seconds',
                'label' => 'Throttle Window (Seconds)',
                'type' => 'number',
                'required' => true,
                'placeholder' => '60',
                'hint' => 'Minimum delay between repeated submissions from the same email or IP on one article.',
            ],
            [
                'key' => 'comments.auto_reject_spam',
                'label' => 'Automatically Reject Spam',
                'type' => 'toggle',
                'hint' => 'If disabled, suspected spam stays pending with a flag for moderator review.',
            ],
            [
                'key' => 'comments.blocked_words',
                'label' => 'Blocked Words',
                'type' => 'textarea',
                'rows' => 5,
                'placeholder' => "casino\ncrypto scam\nbuy followers",
                'hint' => 'Enter one word or phrase per line, or separate values with commas.',
            ],
            [
                'key' => 'comments.blocked_emails',
                'label' => 'Blocked Emails or Domains',
                'type' => 'textarea',
                'rows' => 4,
                'placeholder' => "bad@example.com\nspamdomain.test",
                'hint' => 'Supports exact email addresses or whole domains.',
            ],
            [
                'key' => 'comments.blocked_ips',
                'label' => 'Blocked IP Addresses',
                'type' => 'textarea',
                'rows' => 4,
                'placeholder' => "203.0.113.10\n198.51.100.5",
                'hint' => 'Exact IP matches are blocked before moderation.',
            ],
        ],
    ],
    [
        'key' => 'seo.defaults',
        'name' => 'SEO Defaults',
        'info' => 'Reserved for global meta title, description, and indexing options.',
        'sort' => 1,
        'fields' => [],
    ],
    [
        'key' => 'media',
        'name' => 'Media',
        'info' => 'Upload rules, image handling, and asset delivery preferences.',
        'sort' => 5,
        'icon' => 'ME',
    ],
    [
        'key' => 'media.images',
        'name' => 'Image Handling',
        'info' => 'Reserved for image quality, size limits, and derivatives.',
        'sort' => 1,
        'fields' => [],
    ],
    [
        'key' => 'email',
        'name' => 'Email',
        'info' => 'Outgoing mail and editorial notification configuration.',
        'sort' => 6,
        'icon' => 'EM',
    ],
    [
        'key' => 'email.delivery',
        'name' => 'Delivery Settings',
        'info' => 'Reserved for sender details, transport setup, and admin notifications.',
        'sort' => 1,
        'fields' => [],
    ],
    [
        'key' => 'cache',
        'name' => 'Cache',
        'info' => 'Application cache, invalidation strategy, and performance placeholders.',
        'sort' => 7,
        'icon' => 'CA',
    ],
    [
        'key' => 'cache.strategy',
        'name' => 'Cache Strategy',
        'info' => 'Reserved for cache toggles, refresh policy, and warmup controls.',
        'sort' => 1,
        'fields' => [],
    ],
];
